package com.psm.Database;

import android.content.Context;
import android.database.sqlite.SQLiteOpenHelper;
import android.database.sqlite.SQLiteDatabase;

public class Source extends SQLiteOpenHelper{	

	public Source(Context context) {
		super(context, DATABASE_NAME, null, DATABASE_VERSION);
	}

	@Override
	public void onCreate(SQLiteDatabase db) {	
		createDatabase(db);
	}

	@Override
	public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
		db.execSQL("DROP TABLE tbl_excipiente");
		db.execSQL("DROP TABLE tbl_activos");
		db.execSQL("DROP TABLE tbl_periodos");
		db.execSQL("DROP TABLE tbl_medicina");
		db.execSQL("DROP TABLE tbl_tratamiento");
		db.execSQL("DROP TABLE tbl_medicinatratamiento");
		db.execSQL("DROP TABLE tbl_horario");
		db.execSQL("DROP TABLE tbl_usuario");
		createDatabase(db);
	}
	
	private void createDatabase(SQLiteDatabase db)
	{
		db.execSQL(TBL_EXCIPIENTE);
		db.execSQL(TBL_ACTIVOS);
		db.execSQL(TBL_PERIODOS);
		db.execSQL(TBL_MEDICINA);
		db.execSQL(TBL_TRATAMIETO);
		db.execSQL(TBL_MEDICINATRATAMIENTO);
		db.execSQL(TBL_HORARIO);
		db.execSQL(TBL_USUARIO);
		//Llenar los catálogos
		for(String[] activo:Activos)
		{
			db.execSQL("Insert into tbl_Activos(Activo,ActivoE,ActivoF) VALUES('"+activo[0].trim()+"','"+activo[1].trim()+"','"+activo[2].trim()+"')");				
		}
		for(String[] excipiente:Excipientes)
		{
			db.execSQL("Insert into tbl_Excipiente(Icon,Excipiente,ExcipienteE,ExcipienteF)" +
					" VALUES('"+excipiente[0].trim()+"','"+excipiente[1].trim()+"','"+excipiente[2].trim()+"','"+excipiente[3].trim()+"')");				
		}
		for(String[] periodo:Periodos)
		{
			db.execSQL("Insert into tbl_Periodo(Periodo,PeriodoE,PeriodoF) VALUES('"+periodo[0].trim()+"','"+periodo[1].trim()+"','"+periodo[2].trim()+"')");				
		}
		
		db.execSQL("Insert Into tbl_medicina(Medicina,Indicacion,ExcipienteId,ActivoId1) VALUES('Tempra','Alivio de dolor y fiebre',5,2)");
		db.execSQL("insert into tbl_usuario(Usuario,Edad,Correo)VALUES('Farmacy',20,'M')");
		
	}
	
	private static final int DATABASE_VERSION = 1;
	private static final String DATABASE_NAME = "FarmacyI.db";
	
	private static final String TBL_EXCIPIENTE =
		"CREATE TABLE tbl_Excipiente ( " +
		"ExcipienteId INTEGER PRIMARY KEY AUTOINCREMENT," +
		"Icon TEXT," +				
		"Excipiente TEXT ," +
		"ExcipienteE TEXT," +
		"ExcipienteF TEXT" +								
		");";	
	
	private static final String TBL_USUARIO = 
		"CREATE TABLE tbl_usuario(" +
		"UsuarioId INTEGER PRIMARY KEY AUTOINCREMENT," +
		"Usuario TEXT NULL," +
		"Edad  INTEGER NULL," +		
		"sexo TEXT NULL" +
		")";	
	
	private static final String TBL_MEDICINA = 
		"CREATE TABLE tbl_medicina (" +
		"MedicinaId INTEGER PRIMARY KEY," +
		"Medicina TEXT ," +		
		"Indicacion TEXT ," +
		"ExcipienteId INT," +
		"ActivoId1 INT "+
		"ActivoId2 INT NULL "+
		");";
	
	private static final String TBL_TRATAMIETO = 
		"CREATE TABLE tbl_tratamiento ( " +
		"TratamientoId INTEGER PRIMARY KEY, " +
		"Tratamiento TEXT NOT NULL, " +
		"Enfermedad TEXT NOT NULL, " +
		"UsuarioId INTEGER ," +
		"FecAlta DATE" +
		")"	;
	
	private static final String TBL_MEDICINATRATAMIENTO = 
		"CREATE TABLE tbl_MedicinaTratamiento ( " +
		"RelacionId INTEGER PRIMARY KEY AUTOINCREMENT," +
		"TratamientoId INTEGER NOT NULL ," +
		"MedicinaId INTEGER NOT NULL, " +
		"DosisExcipiente INTGER NOT NULL, " +
		"FecIni DATE NOT NULL, " +
		"PeriodoDuracion INTEGER, " +
		"PeriodosDuracion INTEGER, " +
		"PeriodoIntervalo INTEGER, " +
		"PeriodosIntervalo INTEGER," +
		"TomasTotales INTEGER);";
	
	private static final String TBL_HORARIO = 
		"CREATE TABLE tbl_horario(" +
		"RelacionId INTEGER," +
		"TomaNo INTEGER," +
		"Fecha DATE," +
		"Hora DATE," +
		"Tomada INTEGER," +
		"Reprogramada INTEGER" +
		");";
	private static final String TBL_PERIODOS = 
		"CREATE TABLE tbl_Periodo (" +
		"PeriodoId INTEGER PRIMARY KEY AUTOINCREMENT, " +
		"Periodo TEXT, " +
		"PeriodoE TEXT," +
		"PeriodoF" +
		");";
	
	private static final String TBL_ACTIVOS=
		"CREATE TABLE tbl_Activos("+
		"ActivoId INTEGER PRIMARY KEY AUTOINCREMENT," +
		"Activo TEXT," +
		"ActivoE TEXT," +
		"ActivoF TEXT);";
	
	private static final String[][]Periodos={
		{"Horas","Hours","Heures"},
		{"Días","Days","Journées"},
		{"Semanas","Weeks","Semaines"},
		{"Meses","Months","Mois"},
		{"Años","Years","Ans"}};
	
	private static final String[][]Excipientes={
		{"A","Gotas","Drops","Gouttes"},
		{"B","Jarabe","Syrup","Sirop"},
		{"C","Té","Tea","Tisanas"},
		{"B","Elixir","Elixir","Élixir"},
		{"B","Suspensión","Suspension","Suspension"},
		{"D","Parche","Patch","Pièce"},
		{"B","Bebibles","Drinkable","Potable"},
		{"H","Comprimidos","Tablet","Comprimés"},
		{"E","Cápsulas","Capsules","Capsules"},
		{"C","Granulados","Granules","Granules"},
		{"K","Píldoras","Pill","Pilule"},
		{"H","Pastillas","Pills","Pills"},
		{"J","Intravenosa","Intravenous","Intraveineuse"},
		{"J","Intraarterial","Intraarterial","Intra-artérielle"},
		{"J","Intramuscular","Intramuscular","Intramusculaire"},
		{"L","Supositorios","Suppositories","Suppositoires"},
		{"C","Loción","Lotion","Lotion"},
		{"C","Polvos","Powder","Poudre"},
		{"G","Pastasta","Pâtes"},
		{"G","Ungüento","Ointment","Pommade"},
		{"G","Gel","Gel","Gel"},
		{"I","Spay","Spray","Spray"},
		{"F","Inhalador","Inhaler","Inhalateur"},
		{"M","Ampolleta","Vial","Ampoule"}
	};
	
	private static final String[][] Activos={
		{"Abacavir","Abacavir","Abacavir"},
		{"Acarbosa","Acarbose","L´acarbose"},
		{"Aceclofenaco","Aceclofenac","Acéclofénac"},
		{"Aceite de ricino	","	Castor oil 	","	Huile de ricin 	"},
		{"Acenocumarol	","	acenocumarol 	","	Acenocumarol 	"},
		{"Acetato potásico	","	Potassium acetate 	","	L´acétate de potassium 	"},
		{"Acetilcisteína	","	Acetylcysteine 	","	Acétylcystéine 	"},
		{"Aciclovir	","	Acyclovir 	","	Acyclovir 	"},
		{"Ácido acetilsalicílico	","	Aspirin 	","	Aspirine 	"},
		{"Ácido alendrónico	","	Alendronate 	","	L´alendronate 	"},
		{"Ácido ascórbico	","	Ascorbic acid 	","	L´acide ascorbique 	"},
		{"Ácido azelaico	","	Azelaic acid 	","	L´acide azélaïque 	"},
		{"Ácido carglúmico	","	Aarglumic acid 	","	Acide carglumique 	"},
		{"Ácido cítrico anhidro	","	Anhydrous Citric Acid 	","	Acide citrique anhydre 	"},
		{"Ácido clavulánico	","	Clavulanate 	","	Clavulanate 	"},
		{"Ácido cromoglícico	","	Cromoglicic acid 	","	Acide Cromoglicic 	"},
		{"Ácido dobesílico	","	Acid dobesílico 	","	Dobesílico acide 	"},
		{"Ácido fólico	","	Folic acid 	","	L´acide folique 	"},
		{"Ácido fusídico	","	Fusidic acid 	","	L´acide fusidique 	"},
		{"Ácido hialurónico	","	Hyaluronan 	","	L´acide hyaluronique 	"},
		{"Ácido ibandrónico	","	Ibandronic acid 	","	L´acide ibandronique 	"},
		{"Ácido láctico	","	Lactic acid 	","	acide lactique 	"},
		{"Ácido micofenólico	","	Mycophenolic acid 	","	L´acide mycophénolique 	"},
		{"Ácido picosulfúrico	","	Acid picosulfúrico 	","	picosulfúrico acide 	"},
		{"Ácido risedrónico	","	Risedronic acid 	","	Acide risédronique 	"},
		{"Ácido salicílico	","	Salicylic acid 	","	L´acide salicylique 	"},
		{"Ácido tiludrónico	","	Tiludronic acid 	","	L´acide tiludronique 	"},
		{"Ácido tranexámico	","	Tranexamic acid 	","	L´acide tranexamique 	"},
		{"Ácido ursodeoxicólico	","	Ursodeoxycholic acid 	","	L´acide ursodésoxycholique 	"},
		{"Ácido ursodesoxicólico	","	Ursodeoxycholic acid 	","	L´acide ursodésoxycholique 	"},
		{"Ácido valproico	","	Valproic acid 	","	L´acide valproïque 	"},
		{"Ácido zoledrónico	","	Zoledronic acid 	","	L´acide zolédronique 	"},
		{"Adapaleno	","	Adapalene 	","	Adapalène 	"},
		{"Adefovir	","	Adefovir 	","	L´adéfovir 	"},
		{"Adenosina	","	Adenosine 	","	adénosine 	"},
		{"Agomelatina	","	Agomelatine 	","	L´agomélatine 	"},
		{"Albendazol	","	Albendazole 	","	Albendazole 	"},
		{"Alcanfor	","	Camphor 	","	Camphre 	"},
		{"Alcohol diclorobencílico	","	Alcohol dichlorobenzyl 	","	Dichlorobenzylique 	"},
		{"Alcohol polivinílico	","	Polyvinyl Alcohol 	","	Alcool de polyvinyle 	"},
		{"Alfacalcidol	","	Alfacalcidol 	","	Alfacalcidol 	"},
		{"Alfuzosina	","	Alfuzosin 	","	L´alfuzosine 	"},
		{"Alimemazina	","	Alimemazine 	","	Alimémazine 	"},
		{"Aliskiren	","	Aliskiren 	","	L´aliskiren 	"},
		{"Alitretinoína	","	Alitretinoin 	","	Alitrétinoïne 	"},
		{"Almagato	","	Almagate 	","	Almagate 	"},
		{"Almotriptán	","	Almotriptan 	","	Almotriptan 	"},
		{"Alopurinol	","	Allopurinol 	","	Allopurinol 	"},
		{"Alprazolam	","	Alprazolam 	","	Alprazolam 	"},
		{"Altizida	","	Altizida 	","	Altizida 	"},
		{"Aluminio	","	Aluminum 	","	Aluminium 	"},
		{"Ambrisentan	","	Ambrisentan 	","	L´ambrisentan 	"},
		{"Ambroxol	","	Ambroxol 	","	Ambroxol 	"},
		{"Amikacina	","	Amikacin 	","	Amikacine 	"},
		{"Amilmetacresol	","	Amylmetacresol 	","	Amylmétacrésol 	"},
		{"Amilorida	","	Amiloride 	","	Amiloride 	"},
		{"Amiodarona	","	Amiodarone 	","	Amiodarone 	"},
		{"Amisulprida	","	Amisulpride 	","	Amisulpride 	"},
		{"Amitriptilina	","	Amitriptyline 	","	Amitriptyline 	"},
		{"Amlodipino	","	Amlodipine 	","	Amlodipine 	"},
		{"Amorolfina	","	Amorolfine 	","	Amorolfine 	"},
		{"Amoxicilina	","	Amoxicillin 	","	Amoxicilline 	"},
		{"Anagrelida	","	Anagrelide 	","	Anagrelide 	"},
		{"Anastrozol	","	Anastrozole 	","	L´anastrozole 	"},
		{"Anfotericina B	","	Amphotericin B 	","	Amphotéricine B 	"},
		{"Antimonio	","	Antimony 	","	Antimoine 	"},
		{"Apraclonidina	","	Apraclonidine 	","	Apraclonidine 	"},
		{"Aripiprazol	","	Aripiprazole 	","	L´aripiprazole 	"},
		{"Arnica montana	","	Arnica montana 	","	Arnica montana 	"},
		{"Arteméter	","	Artemether 	","	Artéméther 	"},
		{"Asenapina	","	Asenapine 	","	Asénapine 	"},
		{"Atenolol	","	Atenolol 	","	Aténolol 	"},
		{"Atomoxetina	","	Atomoxetine 	","	L´atomoxétine 	"},
		{"Atorvastatina	","	Atorvastatin 	","	L´atorvastatine 	"},
		{"Atovacuona	","	Atovaquone 	","	Atovaquone 	"},
		{"Atropina	","	Atropine 	","	L´atropine 	"},
		{"Azatioprina	","	Azathioprine 	","	Azathioprine 	"},
		{"Azelastina	","	Azelastine 	","	Azelastine 	"},
		{"Azitromicina	","	Azithromycin 	","	Azithromycine 	"},
		{"Bacitracina	","	Bacitracin 	","	Bacitracin 	"},
		{"Baclofeno	","	Baclofen 	","	Le baclofène 	"},
		{"Bálsamo del Perú	","	Balsam of Peru 	","	Baume du Pérou 	"},
		{"Bambuterol	","	Bambuterol 	","	Bambuterol 	"},
		{"Barnidipino	","	Barnidipine 	","	Barnidipine 	"},
		{"Beclometasona	","	Beclomethasone 	","	Béclométhasone 	"},
		{"Bemiparina	","	Bemiparin 	","	Bémiparine 	"},
		{"Benazepril	","	Benazepril 	","	Benazepril 	"},
		{"Bencetonio	","	Benzethonium 	","	Benzethonium 	"},
		{"Bencidamina	","	Benzydamine 	","	Benzydamine 	"},
		{"Benserazida	","	Benserazide 	","	Bensérazide 	"},
		{"Bentazepam	","	Bentazepam 	","	Bentazepam 	"},
		{"Benzalconio	","	Benzalkonium 	","	Benzalkonium 	"},
		{"Benzbromarona	","	Benzbromarone 	","	Benzbromarone 	"},
		{"Benzocaína	","	Benzocaine 	","	Benzocaïne 	"},
		{"Betahistina	","	Betahistine 	","	Bétahistine 	"},
		{"Betametasona	","	Betamethasone 	","	Bétaméthasone 	"},
		{"Bexaroteno	","	Bexarotene 	","	Bexarotene 	"},
		{"Bezafibrato	","	Bezafibrate 	","	Bézafibrate 	"},
		{"Bicalutamida	","	Bicalutamide 	","	Bicalutamide 	"},
		{"Bifonazol	","	Bifonazol 	","	Bifonazol 	"},
		{"Bilastina	","	Bilastina 	","	Bilastina 	"},
		{"Biotina	","	Biotin 	","	Biotine 	"},
		{"Bisacodilo	","	Bisacodyl 	","	Bisacodyl 	"},
		{"Bisoprolol	","	Bisoprolol 	","	Bisoprolol 	"},
		{"Brea hulla	","	Brea tar 	","	Brea tar 	"},
		{"Brimonidina	","	Brimonidine 	","	Brimonidine 	"},
		{"Brinzolamida	","	Brinzolamide 	","	Brinzolamide 	"},
		{"Brivudina	","	Brivudine 	","	Brivudine 	"},
		{"Bromazepam	","	Bromazepam 	","	Bromazépam 	"},
		{"Bromfeniramina	","	Bromfeniramina 	","	Bromfeniramina 	"},
		{"Bromocriptina	","	Bromocriptine 	","	Bromocriptine 	"},
		{"Budesónida	","	Budesonide 	","	Budésonide 	"},
		{"Bumetanida	","	Bumetanide 	","	Bumetanide 	"},
		{"Bupivacaína	","	Bupivacaine 	","	La bupivacaïne 	"},
		{"	Buprenorfina	","	Buprenorphine 	","	Buprénorphine 	"},
		{"Bupropión	","	Bupropion 	","	Le bupropion 	"},
		{"	Buspirona	","	Buspirone 	","	Buspirone 	"},
		{"	Cabergolina	","	Cabergoline 	","	Cabergoline 	"},
		{"	Cadexómero	","	Cadexomer 	","	Cadexomère 	"},
		{"	Cafeína	","	Caffeine 	","	Caféine 	"},
		{"	Calamina	","	Calamine 	","	Calamine 	"},
		{"	Calcio	","	Calcium 	","	Calcium 	"},
		{"	Calcipotriol	","	Calcipotriol 	","	Calcipotriol 	"},
		{"	Calcitonina	","	Calcitonin 	","	La calcitonine 	"},
		{"	Calcitriol	","	Calcitriol 	","	Calcitriol 	"},
		{"	Candesartán	","	Candesartan 	","	Candésartan 	"},
		{"	Capsaicina	","	Capsaicin 	","	La capsaïcine 	"},
		{"	Capsicum	","	Capsicum 	","	Piment doux 	"},
		{"	Captopril	","	Captopril 	","	Captopril 	"},
		{"	Carbamazepina	","	Carbamazepine 	","	Carbamazépine 	"},
		{"	Carbenoxolona	","	Carbenoxolone 	","	Carbenoxolone 	"},
		{"	Carbidopa	","	Carbidopa 	","	Carbidopa 	"},
		{"	Carbinoxamina	","	Carbinoxamine 	","	Carbinoxamine 	"},
		{"	Carbocisteína	","	Carbocysteine 	","	Carbocystéine 	"},
		{"	Carisoprodol	","	Carisoprodol 	","	Carisoprodol 	"},
		{"	Carmelosa	","	Carmelose 	","	Carmelose 	"},
		{"	Carteolol	","	Carteolol 	","	Carteolol 	"},
		{"	Carvedilol	","	Carvedilol 	","	Carvédilol 	"},
		{"	Cassia angustifolia	","	Cassia angustifolia 	","	Cassia angustifolia 	"},
		{"	Cefaclor	","	Cefaclor 	","	Cefaclor 	"},
		{"	Cefalexina	","	Cephalexin 	","	Cephalexin 	"},
		{"	Cefditoren	","	Cefditoren 	","	Cefditoren 	"},
		{"	Cefditoren pivoxilo	","	Cefditoren pivoxil 	","	Cefditorène pivoxil 	"},
		{"	Cefixima	","	Cefixime 	","	Cefixime 	"},
		{"	Cefonicid	","	Cefonicid 	","	Céfonicide 	"},
		{"	Cefotaxima	","	cefotaxime 	","	Céfotaxime 	"},
		{"	Cefpodoxima	","	Cefpodoxime 	","	Cefpodoxime 	"},
		{"	Ceftriaxona	","	Ceftriaxone 	","	Ceftriaxone 	"},
		{"	Cefuroxima	","	Cefuroxime 	","	Céfuroxime 	"},
		{"	Celecoxib	","	Celecoxib 	","	Le célécoxib 	"},
		{"	Celiprolol	","	Celiprolol 	","	Celiprolol 	"},
		{"	Cetirizina	","	Cetirizine 	","	La cétirizine 	"},
		{"	Cianocobalamina	","	Cyanocobalamin 	","	Cyanocobalamin 	"},
		{"	Ciclobenzaprina	","	Cyclobenzaprine 	","	Cyclobenzaprine 	"},
		{"	Ciclopirox	","	Ciclopirox 	","	Ciclopirox 	"},
		{"	Cicloporina	","	Cicloporina 	","	Cicloporina 	"},
		{"	Cilastatina	","	Cilastatin 	","	Cilastatin 	"},
		{"	Cilazapril	","	Cilazapril 	","	Cilazapril 	"},
		{"	Cilostazol	","	Cilostazol 	","	Cilostazol 	"},
		{"	Cimetidina	","	Cimetidine 	","	Cimétidine 	"},
		{"	Cimicifuga racemosa	","	Cimicifuga racemosa 	","	Cimicifuga racemosa 	"},
		{"	Cineol	","	Cineol 	","	Cineol 	"},
		{"	Cinitaprida	","	Cinitapride 	","	Cinitapride 	"},
		{"	Ciprofloxacino	","	Ciprofloxacin 	","	Ciprofloxacine 	"},
		{"	Ciproheptadina	","	Cyproheptadine 	","	Cyproheptadine 	"},
		{"	Ciproterona	","	Cyproterone 	","	Cyprotérone 	"},
		{"	Cisaprida	","	Cisapride 	","	Cisapride 	"},
		{"	Cisplatino	","	Cisplatin 	","	Cisplatine 	"},
		{"	Citalopram	","	Citalopram 	","	Citalopram 	"},
		{"	Citicolina	","	Citicoline 	","	Citicoline 	"},
		{"	Citrato trisódico	","	Trisodium citrate 	","	Citrate trisodique 	"},
		{"	Claritromicina	","	Clarithromycin 	","	Clarithromycine 	"},
		{"	Cleboprida	","	Clebopride 	","	Clébopride 	"},
		{"	Clindamicina	","	Clindamycin 	","	Clindamycine 	"},
		{"	Clioquinol	","	Clioquinol 	","	Clioquinol 	"},
		{"	Clobazam	","	Clobazam 	","	Clobazam 	"},
		{"	Clobetasol	","	Clobetasol 	","	Clobétasol 	"},
		{"	Clobetasona	","	Clobetasone 	","	Clobétasone 	"},
		{"	Clocinizina	","	Clocinizina 	","	Clocinizina 	"},
		{"	Clofazimina	","	Clofazimine 	","	Clofazimine 	"},
		{"	Clomipramina	","	Clomipramine 	","	Clomipramine 	"},
		{"	Clonazepam	","	Clonazepam 	","	Le clonazépam 	"},
		{"	Clonidina	","	Clonidine 	","	Clonidine 	"},
		{"	Clonixino	","	Clonixino 	","	Clonixino 	"},
		{"	Cloperastina	","	Cloperastine 	","	Clopérastine 	"},
		{"	Clopidogrel	","	Clopidogrel 	","	Clopidogrel 	"},
		{"	Clorazepato dipotásico	","	Clorazepate dipotassium 	","	Clorazépate dipotassique 	"},
		{"	Clorfenamina	","	Clorfenamina 	","	Clorfenamina 	"},
		{"	Clorhexidina	","	Chlorhexidine 	","	Chlorhexidine 	"},
		{"	Clormadinona	","	Chlormadinone 	","	Chlormadinone 	"},
		{"	Clorpromazina	","	Chlorpromazine 	","	Chlorpromazine 	"},
		{"	Clortalidona	","	Chlorthalidone 	","	Chlorthalidone 	"},
		{"	Clostridiopeptidasa	","	Clostridiopeptidase 	","	Clostridiopeptidase 	"},
		{"	Clotiazepam	","	Clotiazepam 	","	Clotiazépam 	"},
		{"	Clotrimazol	","	Clotrimazole 	","	Clotrimazole 	"},
		{"	Cloxacilina	","	Cloxacillin 	","	Cloxacillin 	"},
		{"	Clozapina	","	Clozapine 	","	Clozapine 	"},
		{"	Codeína	","	Codeine 	","	Codéine 	"},
		{"	Colchicina	","	Colchicine 	","	Colchicine 	"},
		{"	Colecalciferol	","	Cholecalciferol 	","	Cholécalciférol 	"},
		{"	Condroitín	","	Chondroitin 	","	Chondroïtine 	"},
		{"	Cúrcuma	","	Turmeric 	","	Curcuma 	"},
		{"	Dabigatrán	","	Dabigatran 	","	Le dabigatran 	"},
		{"	Dapoxetina	","	Dapoxetine 	","	Dapoxetine 	"},
		{"	Deanol	","	Deanol 	","	Déanol 	"},
		{"	Deflazacort	","	Deflazacort 	","	Deflazacort 	"},
		{"	Delapril	","	Delapril 	","	Delapril 	"},
		{"	Dequalinio	","	Dequalinium 	","	Déqualinium 	"},
		{"	Desloratadina	","	Desloratadine 	","	Desloratadine 	"},
		{"	Desmopresina	","	Desmopressin 	","	La desmopressine 	"},
		{"	Desogestrel	","	Desogestrel 	","	Désogestrel 	"},
		{"	Dexametasona	","	Dexamethasone 	","	Dexaméthasone 	"},
		{"	Dexbromfeniramina	","	Dexbrompheniramine 	","	Dexbromphéniramine 	"},
		{"	Dexclorfeniramina	","	Dexchlorpheniramine 	","	Dexchlorpheniramine 	"},
		{"	Dexibuprofeno	","	Dexibuprofen 	","	Dexibuprofen 	"},
		{"	Dexketoprofeno	","	Dexketoprofen 	","	Dexketoprofen 	"},
		{"	Dextrometorfano	","	Dextromethorphan 	","	Dextrométhorphane 	"},
		{"	Dextropropoxifeno	","	Dextropropoxyphene 	","	Dextropropoxyphène 	"},
		{"	Diacereína	","	Diacerein 	","	Diacéréine 	"},
		{"	Diacetil-midecamicina	","	Diacetyl-midecamycin 	","	Diacétyle-midécamycine 	"},
		{"	Diazepam	","	Diazepam 	","	Diazépam 	"},
		{"	Dicicloverina	","	Dicycloverine 	","	Dicyclovérine 	"},
		{"	Diclofenaco	","	Diclofenac 	","	Diclofenac 	"},
		{"	Dienogest	","	Dienogest 	","	Dienogest 	"},
		{"	Difenhidramina	","	Diphenhydramine 	","	Diphenhydramine 	"},
		{"	Digoxina	","	Digoxin 	","	Digoxine 	"},
		{"	Dihidrocodeína	","	Dihydrocodeine 	","	Dihydrocodeine 	"},
		{"	Dihidroergotamina	","	Dihydroergotamine 	","	Dihydroergotamine 	"},
		{"	Diltiazem	","	Diltiazem 	","	Diltiazem 	"},
		{"	Dimemorfano	","	Dimemorfano 	","	Dimemorfano 	"},
		{"	Dimenhidrinato	","	Dimenhydrinate 	","	Dimenhydrinate 	"},
		{"	Dimeticona	","	Dimethicone 	","	Dimethicone 	"},
		{"	Dimetindeno	","	Dimethindene 	","	Dimethindene 	"},
		{"	Dinoprostona	","	Dinoprostone 	","	Dinoprostone 	"},
		{"	Diosmina	","	Diosmin 	","	Diosmin 	"},
		{"	Dipiridamol	","	Dipyridamole 	","	Dipyridamole 	"},
		{"	Ditranol	","	Dithranol 	","	Dithranol 	"},
		{"	Dobutamina	","	Dobutamine 	","	Dobutamine 	"},
		{"	Domperidona	","	Domperidone 	","	La dompéridone 	"},
		{"	Donepezilo	","	Donepezil 	","	Donépézil 	"},
		{"	Dopamina	","	Dopamine 	","	Dopamine 	"},
		{"	Dornasa alfa	","	Dornase alfa 	","	Dornase alfa 	"},
		{"	Dorzolamida	","	Dorzolamide 	","	Le dorzolamide 	"},
		{"	Doxazosina	","	Doxazosin 	","	Doxazosine 	"},
		{"	Doxiciclina	","	Doxycycline 	","	Doxycycline 	"},
		{"	Doxilamina	","	Doxylamine 	","	Doxylamine 	"},
		{"	Drosera rotundifolia	","	Drosera rotundifolia 	","	Drosera rotundifolia 	"},
		{"	Drospirenona	","	Drospirenone 	","	Drospirénone 	"},
		{"	Duloxetina	","	Duloxetine 	","	La duloxétine 	"},
		{"	Dutasterida	","	Dutasteride 	","	Dutastéride 	"},
		{"	Ebastina	","	Ebastine 	","	Ebastine 	"},
		{"	Eberconazol	","	Eberconazole 	","	Eberconazole 	"},
		{"	Echinacea angustifolia	","	Echinacea angustifolia 	","	Echinacea angustifolia 	"},
		{"	Efavirenz	","	Efavirenz 	","	Efavirenz 	"},
		{"	Efedrina	","	Ephedrine 	","	L´éphédrine 	"},
		{"	Eflornitina	","	Eflornithine 	","	Eflornithine 	"},
		{"	Elcatonina	","	Elcatonin 	","	Elcatonine 	"},
		{"	Eletriptán	","	Eletriptan 	","	Eletriptan 	"},
		{"	Emedastina	","	Emedastine 	","	Emedastine 	"},
		{"	Emtricitabina	","	Emtricitabine 	","	L´emtricitabine 	"},
		{"	Enalapril	","	Enalapril 	","	Énalapril 	"},
		{"	Enoxaparina	","	Enoxaparin 	","	Énoxaparine 	"},
		{"	Enoxolona	","	Enoxolone 	","	Enoxolone 	"},
		{"	Entacapona	","	Entacapone 	","	L´entacapone 	"},
		{"	Epinastina	","	Epinastine 	","	Epinastine 	"},
		{"	Epinefrina	","	Epinephrine 	","	Épinéphrine 	"},
		{"	Eplerenona	","	Eplerenone 	","	L´éplérénone 	"},
		{"	Eprosartán	","	Eprosartan 	","	Eprosartan 	"},
		{"	Ergotamina	","	Ergotamine 	","	Ergotamine 	"},
		{"	Eritromicina	","	Erythromycin 	","	Érythromycine 	"},
		{"	Erlotinib	","	Erlotinib 	","	L´erlotinib 	"},
		{"	Escina	","	Escin 	","	Escine 	"},
		{"	Escitalopram	","	Escitalopram 	","	Escitalopram 	"},
		{"	Escopolamina	","	Scopolamine 	","	Scopolamine 	"},
		{"	Esencia de clavo	","	Clove 	","	Clou de girofle 	"},
		{"	Esencia Eucalipto	","	Eucalyptus essence 	","	Eucalyptus essence 	"},
		{"	Esencia Menta	","	Essence Mint 	","	Essence Monnaie 	"},
		{"	Esencia Pino	","	Essence Pino 	","	Essence Pino 	"},
		{"	Esomeprazol	","	Esomeprazole 	","	L´ésoméprazole 	"},
		{"	Espiramicina	","	Spiramycin 	","	Spiramycine 	"},
		{"	Espironolactona	","	Spironolactone 	","	Spironolactone 	"},
		{"	Estavudina	","	Stavudine 	","	Stavudine 	"},
		{"	Estradiol	","	Estradiol 	","	Estradiol 	"},
		{"	Estramustina	","	Estramustine 	","	Estramustine 	"},
		{"	Estreptodornasa	","	Streptodornase 	","	Streptodornase 	"},
		{"	Estreptoquinasa	","	Streptokinase 	","	Streptokinase 	"},
		{"	Estrógenos conjugados	","	Conjugated estrogens 	","	Les œstrogènes conjugués 	"},
		{"	Etambutol	","	Ethambutol 	","	Éthambutol 	"},
		{"	Etinilestradiol	","	Ethinylestradiol 	","	Éthinylestradiol 	"},
		{"	Etofenamato	","	Etofenamate 	","	Étofénamate 	"},
		{"	Etonogestrel	","	Etonogestrel 	","	Etonogestrel 	"},
		{"	Etopósido	","	Etoposide 	","	Étoposide 	"},
		{"	Etoricoxib	","	Etoricoxib 	","	Étoricoxib 	"},
		{"	Eucalipto	","	Eucalyptus 	","	Eucalyptus 	"},
		{"	Exemestano	","	Exemestane 	","	L´exémestane 	"},
		{"	Extracto de Centella asiática	","	Centella asiatica extract 	","	Extrait de Centella asiatica 	"},
		{"	Ezetimiba	","	Ezetimibe 	","	Ezetimibe 	"},
		{"	Famciclovir	","	Famciclovir 	","	Famciclovir 	"},
		{"	Famotidina	","	Famotidine 	","	Famotidine 	"},
		{"	Felodipino	","	Felodipine 	","	Félodipine 	"},
		{"	Fenilefrina	","	Phenylephrine 	","	Phényléphrine 	"},
		{"	Fenilpropanolamina	","	Phenylpropanolamine 	","	Phénylpropanolamine 	"},
		{"	Fenitoína	","	Phenytoin 	","	Phénytoïne 	"},
		{"	Fenobarbital	","	Phenobarbital 	","	Phénobarbital 	"},
		{"	Fenofibrato	","	Fenofibrate 	","	Fénofibrate 	"},
		{"	Fenol	","	Phenol 	","	Phénol 	"},
		{"	Fentanilo	","	Fentanyl 	","	Fentanyl 	"},
		{"	Ferrimanitol ovoalbúmina	","	Ferrimanitol ovalbumin 	","	Ferrimanitol ovalbumine 	"},
		{"	Ferroglicina	","	Ferroglicina 	","	Ferroglicina 	"},
		{"	Fesoterodina	","	Fesoterodine 	","	Fésotérodine 	"},
		{"	Fexofenadina	","	Fexofenadine 	","	Fexofénadine 	"},
		{"	Finasterida	","	Finasteride 	","	Finasteride 	"},
		{"	Fitomenadiona	","	Phytomenadione 	","	Phytomenadione 	"},
		{"	Flecainida	","	Flecainide 	","	Flécaïnide 	"},
		{"	Flubendazol	","	Flubendazole 	","	Flubendazole 	"},
		{"	Fluconazol	","	Fluconazole 	","	Fluconazole 	"},
		{"	Fludarabina	","	Fludarabine 	","	Fludarabine 	"},
		{"	Flufenazina	","	Fluphenazine 	","	Fluphénazine 	"},
		{"	Flumazenilo	","	Flumazenil 	","	Le flumazénil 	"},
		{"	Flunarizina	","	Flunarizina 	","	Flunarizina 	"},
		{"	Flunitrazepam	","	Flunitrazepam 	","	Flunitrazépam 	"},
		{"	Fluocinolona acetónido	","	Fluocinolone acetonide 	","	Acétonide de fluocinolone 	"},
		{"	Fluocortina	","	Fluocortin 	","	Fluocortin 	"},
		{"	Fluoxetina	","	Fluoxetine 	","	La fluoxétine 	"},
		{"	Flupentixol	","	Flupentixol 	","	Flupentixol 	"},
		{"	Flurazepam	","	Flurazepam 	","	Flurazepam 	"},
		{"	Flutamida	","	Flutamide 	","	Flutamide 	"},
		{"	Fluticasona	","	Fluticasone 	","	Fluticasone 	"},
		{"	Flutrimazol	","	Flutrimazole 	","	Flutrimazole 	"},
		{"	Fluvastatina	","	Fluvastatin 	","	Fluvastatine 	"},
		{"	Fluvoxamina	","	Fluvoxamine 	","	Fluvoxamine 	"},
		{"	Formoterol	","	Formoterol 	","	Formotérol 	"},
		{"	Fosfomicina	","	Fosfomycin 	","	La fosfomycine 	"},
		{"	Fosinopril	","	Fosinopril 	","	Fosinopril 	"},
		{"	Frovatriptán	","	Frovatriptan 	","	Frovatriptan 	"},
		{"	Fulvestrant	","	Fulvestrant 	","	Le fulvestrant 	"},
		{"	Furosemida	","	Furosemide 	","	Furosémide 	"},
		{"	Gabapentina	","	Fabapentin 	","	La gabapentine 	"},
		{"	GABOB	","	GABOB 	","	GABOB 	"},
		{"	Galantamina	","	Galantamine 	","	Galantamine 	"},
		{"	Ganciclovir	","	Ganciclovir 	","	Ganciclovir 	"},
		{"	Gelatina	","	Gelatin 	","	Gélatine 	"},
		{"	Gelsemium sempervirens	","	Gelsemium sempervirens 	","	sempervirens Gelsemium 	"},
		{"	Gemfibrozilo	","	Gemfibrozil 	","	Gemfibrozil 	"},
		{"	Gentamicina	","	Gentamicin 	","	Gentamicine 	"},
		{"	Gestodeno	","	Gestodene 	","	Gestodène 	"},
		{"	Ginkgo biloba	","	Ginkgo biloba 	","	Ginkgo biloba 	"},
		{"	Glibenclamida	","	Glibenclamide 	","	Glibenclamide 	"},
		{"	Glicerol	","	Glycerol 	","	Glycérol 	"},
		{"	Glicina	","	Glycine 	","	Glycine 	"},
		{"	Gliclazida	","	Gliclazide 	","	Gliclazide 	"},
		{"	Glimepirida	","	Glimepiride 	","	Glimépiride 	"},
		{"	Glucagón	","	Glucagon 	","	Glucagon 	"},
		{"	Glucosa	","	Glucose 	","	Glucose 	"},
		{"	Glucosamina	","	Glucosamine 	","	Glucosamine 	"},
		{"	Glucósidos antraquinónicos	","	Anthraquinone glycosides 	","	Glycosides d´anthraquinone 	"},
		{"	Glycine max merr	","	Glycine max merr 	","	Glycine max Merr 	"},
		{"	Goserelina	","	Goserelin 	","	Goséréline 	"},
		{"	Gramicidina	","	Gramicidin 	","	Gramicidine 	"},
		{"	Granisetrón	","	Granisetron 	","	Granisétron 	"},
		{"	Guaifenesina	","	Guaifenesin 	","	Guaifénésine 	"},
		{"	Guayacolato de glicerilo	","	Glyceryl guaiacolate 	","	Glyceryl gaïacolate 	"},
		{"	Haloperidol	","	Haloperidol 	","	Halopéridol 	"},
		{"	Hamamelis	","	Hamamelis 	","	Hamamélis 	"},
		{"	Harpagophytum procumbens	","	Harpagophytum procumbens 	","	Harpagophytum procumbens 	"},
		{"	Hedera helix	","	Hedera helix 	","	Hedera helix 	"},
		{"	Heparina	","	Heparin 	","	Héparine 	"},
		{"	Hesperidina	","	Hesperidin 	","	Hespéridine 	"},
		{"	Hexetidina	","	Hexetidine 	","	Hexetidine 	"},
		{"	Hidralazina	","	Hydralazine 	","	Hydralazine 	"},
		{"	Hidroclorotiazida	","	Hydrochlorothiazide 	","	Hydrochlorothiazide 	"},
		{"	Hidrocortisona	","	Hydrocortisone 	","	Hydrocortisone 	"},
		{"	Hidromorfona	","	Hydromorphone 	","	Hydromorphone 	"},
		{"	Hidroquinona	","	Hydroquinone 	","	Hydroquinone 	"},
		{"	Hidrosmina	","	Hidrosmin 	","	Hidrosmin 	"},
		{"	Hidrotalcita	","	Hydrotalcite 	","	Hydrotalcite 	"},
		{"	Hidroxicarbamida	","	Hydroxyurea 	","	Hydroxyurée 	"},
		{"	Hidroxicloroquina	","	Hydroxychloroquine 	","	Hydroxychloroquine 	"},
		{"	Hidroxizina	","	Hydroxyzine 	","	Hydroxyzine 	"},
		{"	Hidroxocobalamina	","	Hydroxocobalamin 	","	Hydroxocobalamine 	"},
		{"	Hierro	","	Iron 	","	Fer 	"},
		{"	Hierro proteinsuccinilato	","	Iron proteinsuccinilato 	","	Proteinsuccinilato de fer 	"},
		{"	Hioscina	","	Hyoscine 	","	Hyoscine 	"},
		{"	Hipérico	","	Hypericum 	","	Hypericum 	"},
		{"	Hipromelosa	","	Hypromellose 	","	Hypromellose 	"},
		{"	Ibuprofeno	","	Ibuprofen 	","	L´ibuprofène 	"},
		{"	Imidapril	","	Imidapril 	","	Imidapril 	"},
		{"	Imipenem	","	Imipenem 	","	Imipénème 	"},
		{"	Imiquimod	","	Imiquimod 	","	Imiquimod 	"},
		{"	Indapamida	","	Indapamide 	","	Indapamide 	"},
		{"	Ipratropio	","	Ipratropio 	","	Ipratropio 	"},
		{"	Irbesartán	","	Irbesartan 	","	Irbesartan 	"},
		{"	Isoniazida	","	Isoniazid 	","	Isoniazide 	"},
		{"	Isoprenalina	","	Isoprenaline 	","	Isoprenaline 	"},
		{"	Isosorbida	","	Isosorbide 	","	Isosorbide 	"},
		{"	Isotretinoína	","	Isotretinoin 	","	L´isotrétinoïne 	"},
		{"	Isradipino	","	Isradipine 	","	Isradipine 	"},
		{"	Itraconazol	","	Itraconazole 	","	Itraconazole 	"},
		{"	Ivabradina	","	Ivabradine 	","	L´ivabradine 	"},
		{"	Ketazolam	","	Ketazolam 	","	Kétazolam 	"},
		{"	Ketoconazol	","	Ketoconazole 	","	Kétoconazole 	"},
		{"	Ketoprofeno	","	Ketoprofen 	","	Le kétoprofène 	"},
		{"	Ketorolaco	","	Ketorolac 	","	Kétorolac 	"},
		{"	Ketotifeno	","	Ketotifen 	","	Ketotifen 	"},
		{"	Labetalol	","	Kabetalol 	","	Labétalol 	"},
		{"	Lacidipino	","	Kacidipine 	","	Lacidipine 	"},
		{"	Lacosamida	","	Kacosamide 	","	Lacosamide 	"},
		{"	Lactitol	","	Lactitol 	","	Lactitol 	"},
		{"	Lactulosa	","	Lactulose 	","	Lactulose 	"},
		{"	Lamivudina	","	Lamivudine 	","	Lamivudine 	"},
		{"	Lamotrigina	","	Lamotrigine 	","	Lamotrigine 	"},
		{"	Lansoprazol	","	Lansoprazole 	","	lansoprazole 	"},
		{"	Lantano	","	Lanthanum 	","	lanthane 	"},
		{"	Latanoprost	","	Latanoprost 	","	Le latanoprost 	"},
		{"	Laurilsulfato	","	Lauryl 	","	Lauryl 	"},
		{"	Leflunomida	","	Leflunomide 	","	Léflunomide 	"},
		{"	Lercanidipino	","	Lercanidipine 	","	Lercanidipine 	"},
		{"	Letrozol	","	Letrozole 	","	Létrozole 	"},
		{"	Levetiracetam	","	Levetiracetam 	","	Lévétiracétam 	"},
		{"	Levocetirizina	","	Levocetirizine 	","	Lévocétirizine 	"},
		{"	Levodopa	","	Levodopa 	","	Lévodopa 	"},
		{"	Levodropropicina	","	Levodropropicina 	","	Levodropropicina 	"},
		{"	Levodropropizina	","	Levodropropizine 	","	Lévodropropizine 	"},
		{"	Levofloxacino	","	Levofloxacin 	","	La lévofloxacine 	"},
		{"	Levofolinato de calcio	","	Levofolinate 	","	Lévofolinate 	"},
		{"	Levomepromazina	","	Levomepromazine 	","	Levomepromazine 	"},
		{"	Levonorgestrel	","	Levonorgestrel 	","	Lévonorgestrel 	"},
		{"	Levosulpirida	","	Levosulpiride 	","	Levosulpiride 	"},
		{"	Levotiroxina	","	Levothyroxine 	","	Lévothyroxine 	"},
		{"	Lidocaína	","	Lidocaine 	","	Lidocaïne 	"},
		{"	Lindano	","	Lindane 	","	Lindane 	"},
		{"	Linezolid	","	Linezolid 	","	Linézolide 	"},
		{"	Lisina	","	Lysine 	","	Lysine 	"},
		{"	Lisinopril	","	Lisinopril 	","	Lisinopril 	"},
		{"	Lisozima	","	Lysozyme 	","	Lysozyme 	"},
		{"	Lisurida	","	Lisuride 	","	Lisuride 	"},
		{"	Litio	","	Lithium 	","	Lithium 	"},
		{"	Lomefloxacino	","	Lomefloxacin 	","	Lomefloxacin 	"},
		{"	Loperamida	","	Loperamide 	","	Le lopéramide 	"},
		{"	Lopinavir	","	Lopinavir 	","	Lopinavir 	"},
		{"	Loprazolam	","	Loprazolam 	","	Loprazolam 	"},
		{"	Loratadina	","	Loratadine 	","	Loratadine 	"},
		{"	Lorazepam	","	Lorazepam 	","	Lorazepam 	"},
		{"	Lormetazepam	","	Lormetazepam 	","	Lormetazepam 	"},
		{"	Lornoxicam	","	Lornoxicam 	","	Lornoxicam 	"},
		{"	Losartán	","	Losartan 	","	Losartan 	"},
		{"	Lovastatina	","	Lovastatin 	","	Lovastatine 	"},
		{"	Lumefantrina	","	Lumefantrine 	","	Luméfantrine 	"},
		{"	Macrogol 3350	","	Macrogol 3350 	","	Macrogol 3350 	"},
		{"	Macrogol 4000	","	Macrogol 4000 	","	Macrogol 4000 	"},
		{"	Magaldrato	","	Magaldrate 	","	Magaldrate 	"},
		{"	Magnesio	","	Magnesium 	","	Magnésium 	"},
		{"	Manidipino	","	Manidipine 	","	Manidipine 	"},
		{"	Mebendazol	","	Mebendazole 	","	Mébendazole 	"},
		{"	Mebeverina	","	Mebeverine 	","	Mébévérine 	"},
		{"	Medazepam	","	Medazepam 	","	Médazépam 	"},
		{"	Medroxiprogesterona	","	Medroxyprogesterone 	","	Médroxyprogestérone 	"},
		{"	Megestrol	","	Megestrol 	","	Megestrol 	"},
		{"	Melfalán	","	Melphalan 	","	Melphalan 	"},
		{"	Melissa officinalis	","	Melissa officinalis 	","	Melissa officinalis 	"},
		{"	Melitraceno	","	Melitracen 	","	Melitracen 	"},
		{"	Meloxicam	","	Meloxicam 	","	Méloxicam 	"},
		{"	Memantina	","	Memantine 	","	La mémantine 	"},
		{"	Mentol	","	Menthol 	","	Menthol 	"},
		{"	Mepifilina	","	Mepifilina 	","	Mepifilina 	"},
		{"	Mepivacaína	","	Mepivacaine 	","	Mepivacaine 	"},
		{"	Mequitazina	","	Mequitazine 	","	Méquitazine 	"},
		{"	Merbromina	","	Merbromin 	","	Merbromin 	"},
		{"	Mesalazina	","	Mesalazine 	","	Mésalazine 	"},
		{"	Metadona	","	Methadone 	","	La méthadone 	"},
		{"	Metamizol	","	Metamizol 	","	Metamizol 	"},
		{"	Metformina	","	Metformin 	","	La metformine 	"},
		{"	Metilergometrina	","	Methylergometrine 	","	Methylergometrine 	"},
		{"	Metilfenidato	","	Methylphenidate 	","	Le méthylphénidate 	"},
		{"	Metilprednisolona	","	Methylprednisolone 	","	Méthylprednisolone 	"},
		{"	Metipranolol	","	Metipranolol 	","	Metipranolol 	"},
		{"	Metoclopramida	","	Metoclopramide 	","	Métoclopramide 	"},
		{"	Metoprolol	","	Metoprolol 	","	Métoprolol 	"},
		{"	Metotrexato	","	Methotrexate 	","	Le méthotrexate 	"},
		{"	Metronidazol	","	Metronidazole 	","	Le métronidazole 	"},
		{"	Mianserina	","	Mianserin 	","	Miansérine 	"},
		{"	Micofenolato mofetilo	","	Mycophenolate mofetil 	","	Mycophénolate mofétil 	"},
		{"	Miconazol	","	Miconazole 	","	Miconazole 	"},
		{"	Midazolam	","	Midazolam 	","	Midazolam 	"},
		{"	Midodrina	","	Midodrina 	","	Midodrina 	"},
		{"	Mifepristona	","	Mifepristone 	","	Mifépristone 	"},
		{"	Miglitol	","	Miglitol 	","	Miglitol 	"},
		{"	Minoxidil	","	Minoxidil 	","	Minoxidil 	"},
		{"	Mirtazapina	","	Mirtazapine 	","	La mirtazapine 	"},
		{"	Misoprostol	","	Misoprostol 	","	Misoprostol 	"},
		{"	Mizolastina	","	Mizolastine 	","	Mizolastine 	"},
		{"	Moclobemida	","	Moclobemide 	","	Moclobémide 	"},
		{"	Modafinilo	","	Modafinil 	","	Modafinil 	"},
		{"	Mometasona	","	Mometasone 	","	Mometasone 	"},
		{"	Montelukast	","	Montelukast 	","	Montelukast 	"},
		{"	Morfina	","	Morphine 	","	Morphine 	"},
		{"	Morniflumato	","	Morniflumate 	","	Morniflumate 	"},
		{"	Moxifloxacino	","	Moxifloxacin 	","	La moxifloxacine 	"},
		{"	Moxonidina	","	Moxonidine 	","	Moxonidine 	"},
		{"	Mucopolisacaridasa	","	Mucopolisacaridasa 	","	Mucopolisacaridasa 	"},
		{"	Mupirocina	","	Mupirocin 	","	Mupirocin 	"},
		{"	Nabumetona	","	Nabumetone 	","	Mabumétone 	"},
		{"	Nafazolina	","	Naphazoline 	","	Naphazoline 	"},
		{"	Naloxona	","	Naloxone 	","	Naloxone 	"},
		{"	Naproxeno	","	Naproxen 	","	Naproxen 	"},
		{"	Naratriptán	","	Naratriptan 	","	Le naratriptan 	"},
		{"	Nebivolol	","	Nebivolol 	","	Nébivolol 	"},
		{"	Nedocromilo	","	Nedocromil 	","	Nedocromil 	"},
		{"	Neomicina	","	Neomycin 	","	Néomycine 	"},
		{"	Nevirapina	","	Nevirapine 	","	Névirapine 	"},
		{"	Nicardipino	","	Nicardipine 	","	Nicardipine 	"},
		{"	Nicorandil	","	Nicorandil 	","	Le nicorandil 	"},
		{"	Nicotina	","	Nicotine 	","	Nicotine 	"},
		{"	Nifedipino	","	Nifedipine 	","	Nifédipine 	"},
		{"	Nimodipino	","	Nimodipine 	","	Nimodipine 	"},
		{"	Nisoldipino	","	Nisoldipine 	","	Nisoldipine 	"},
		{"	Nistatina	","	Nystatin 	","	Nystatine 	"},
		{"	Nitrendipino	","	Nitrendipine 	","	Nitrendipine 	"},
		{"	Nitrofural	","	Nitrofural 	","	Nitrofural 	"},
		{"	Nitroglicerina	","	Nitroglycerine 	","	Nitroglycérine 	"},
		{"	Norelgestromina	","	Norelgestromin 	","	Norelgestromin 	"},
		{"	Norepinefrina	","	Norepinephrine 	","	Noradrénaline 	"},
		{"	Noretisterona	","	Norethisterone 	","	Norethisterone 	"},
		{"	Norfloxacino	","	Norfloxacin 	","	Norfloxacine 	"},
		{"	Norgestimato	","	Norgestimate 	","	Norgestimate 	"},
		{"	Nortriptilina	","	Nortriptyline 	","	Nortriptyline 	"},
		{"	Octreotida	","	Octreotide 	","	L´octréotide 	"},
		{"	Ofloxacino	","	Ofloxacin 	","	Ofloxacine 	"},
		{"	Olanzapina	","	Olanzapine 	","	Olanzapine 	"},
		{"	Olmesartán medoxomilo	","	Olmesartan medoxomil I 	","	Olmésartan médoxomil je 	"},
		{"	Omeprazol	","	Omeprazole 	","	L´oméprazole 	"},
		{"	Ondansetrón	","	Ondansetron 	","	L´ondansétron 	"},
		{"	Orlistat	","	Orlistat 	","	Orlistat 	"},
		{"	Oseltamivir	","	Oseltamivir 	","	L´oseltamivir 	"},
		{"	Oxcarbazepina	","	Oxcarbazepine 	","	L´oxcarbazépine 	"},
		{"	Oxerutinas	","	Oxerutins 	","	Oxerutins 	"},
		{"	Oxibato de sodio	","	Sodium oxybate 	","	L´oxybate de sodium 	"},
		{"	Oxibutinina	","	Oxybutynin 	","	Oxybutynine 	"},
		{"	Oxicodona	","	Oxycodone 	","	Oxycodone 	"},
		{"	Óxido de magnesio	","	Magnesium oxide 	","	L´oxyde de magnésium 	"},
		{"	Oximetazolina	","	Oxymetazoline 	","	Oxymetazoline 	"},
		{"	Oxitetraciclina	","	Oxytetracycline 	","	Oxytétracycline 	"},
		{"	Oxprenolol	","	Oxprenolol 	","	Oxprenolol 	"},
		{"	Paliperidona	","	Paliperidone 	","	La palipéridone 	"},
		{"	Panax ginseng	","	Panax ginseng 	","	Panax ginseng 	"},
		{"	Pancreatina	","	Pancreatin 	","	Pancreatin 	"},
		{"	Pantoprazol	","	Pantoprazole 	","	Pantoprazole 	"},
		{"	Papaína	","	Papain 	","	La papaïne 	"},
		{"	Paracetamol	","	Paracetamol 	","	Paracétamol 	"},
		{"	Parafina líquida	","	Liquid paraffin 	","	L´huile de paraffine 	"},
		{"	Paricalcitol	","	Paricalcitol 	","	Paricalcitol 	"},
		{"	Paroxetina	","	Paroxetine 	","	Paroxétine 	"},
		{"	Passiflora incarnata	","	Passiflora incarnata 	","	Passiflora incarnata 	"},
		{"	Pelargonium sidoides	","	Pelargonium sidoides 	","	Pelargonium sidoides 	"},
		{"	Penciclovir	","	Penciclovir 	","	Penciclovir 	"},
		{"	Pentamidina	","	Pentamidine 	","	Pentamidine 	"},
		{"	Pentosano polisulfato de sodio	","	Pentosan polysulfate sodium 	","	Polysulfate de pentosan sodique 	"},
		{"	Pentoxifilina	","	Pentoxifylline 	","	Pentoxifylline 	"},
		{"	Pepsina	","	Pepsin 	","	Pepsine 	"},
		{"	Periciazina	","	Pericyazine 	","	Péricyazine 	"},
		{"	Perindopril	","	Perindopril 	","	Perindopril 	"},
		{"	Permetrina	","	Permethrin 	","	Perméthrine 	"},
		{"	Peróxido de benzoílo	","	Benzoyl peroxide 	","	Peroxyde de benzoyle 	"},
		{"	Petidina	","	Pethidine 	","	Péthidine 	"},
		{"	Picosulfato sódico	","	Sodium picosulfate 	","	Picosulfate de sodium 	"},
		{"	Piketoprofeno	","	Piketoprofen 	","	Piketoprofen 	"},
		{"	Pilocarpina	","	Pilocarpine 	","	Pilocarpine 	"},
		{"	Pimecrolimus	","	Pimecrolimus 	","	Pimecrolimus 	"},
		{"	Pimozida	","	Pimozide 	","	Pimozide 	"},
		{"	Pinazepam	","	Pinazepam 	","	Pinazépam 	"},
		{"	Pioglitazona	","	Pioglitazone 	","	Pioglitazone 	"},
		{"	Piperacilina	","	Piperacillin 	","	Pipéracilline 	"},
		{"	Piracetam	","	Piracetam 	","	Piracetam 	"},
		{"	Pirantel	","	Pyrantel 	","	Pyrantel 	"},
		{"	Pirazinamida	","	Pyrazinamide 	","	Pyrazinamide 	"},
		{"	Piridoxina	","	Pyridoxine 	","	Pyridoxine 	"},
		{"	Piroxicam	","	Piroxicam 	","	Piroxicam 	"},
		{"	Pitavastatina	","	Pitavastatin 	","	Pitavastatin 	"},
		{"	Plantago ovata	","	Plantago ovata 	","	Plantago ovata 	"},
		{"	Plata	","	Silver 	","	Argent 	"},
		{"	Podofilotoxina	","	Podophyllotoxin 	","	Podophyllotoxine 	"},
		{"	Poliestireno sulfonato	","	Polystyrene sulfonate 	","	Polystyrène sulfonate 	"},
		{"	Polimixina B	","	Polymyxin B 	","	Polymyxine B 	"},
		{"	Polypodium leucotomos	","	Polypodium leucotomos 	","	Polypodium leucotomos 	"},
		{"	Potasio	","	Potassium 	","	Potassium 	"},
		{"	Povidona	","	Povidone 	","	Povidone 	"},
		{"	Pramipexol	","	Pramipexole 	","	Pramipexole 	"},
		{"	Pravastatina	","	Pravastatin 	","	Pravastatine 	"},
		{"	Prazosina	","	Prazosin 	","	Prazosine 	"},
		{"	Prednisolona	","	Prednisolone 	","	Prednisolone 	"},
		{"	Prednisona	","	Prednisone 	","	Prednisone 	"},
		{"	Pregabalina	","	Pregabalin 	","	La prégabaline 	"},
		{"	Prilocaína	","	Prilocaine 	","	Prilocaïne 	"},
		{"	Progesterona	","	Progesterone 	","	Progestérone 	"},
		{"	Proguanil	","	Proguanil 	","	Proguanil 	"},
		{"	Prometazina	","	Promethazine 	","	Prométhazine 	"},
		{"	Propafenona	","	Propafenone 	","	Propafénone 	"},
		{"	Propifenazona	","	Propyphenazone 	","	Propyphénazone 	"},
		{"	Propofol	","	Propofol 	","	Propofol 	"},
		{"	Propranolol	","	Propranolol 	","	Propranolol 	"},
		{"	Proteasas	","	Proteases 	","	Protéases 	"},
		{"	Pseudoefedrina	","	Pseudoephedrine 	","	Pseudoéphédrine 	"},
		{"	Quazepam	","	Quazepam 	","	Quazépam 	"},
		{"	Quetiapina	","	Quetiapine 	","	Quétiapine 	"},
		{"	Quinagolida	","	Octreotide 	","	L´octréotide 	"},
		{"	Quinapril	","	Quinapril 	","	Quinapril 	"},
		{"	Rabeprazol	","	Rabeprazole 	","	Rabéprazole 	"},
		{"	Racecadotrilo	","	Racecadotril 	","	Racecadotril 	"},
		{"	Raloxifeno	","	Raloxifene 	","	Le raloxifène 	"},
		{"	Ramipril	","	Ramipril 	","	Ramipril 	"},
		{"	Ranitidina	","	Ranitidine 	","	Ranitidine 	"},
		{"	Reboxetina	","	Reboxetine 	","	Reboxetine 	"},
		{"	Repaglinida	","	Repaglinide 	","	Le répaglinide 	"},
		{"	Resorcinol	","	Resorcinol 	","	Résorcinol 	"},
		{"	Retapamulina	","	Retapamulin 	","	Rétapamuline 	"},
		{"	Retinol	","	Retinol 	","	Rétinol 	"},
		{"	Ribavirina	","	Ribavirin 	","	Ribavirine 	"},
		{"	Riboflavina	","	Riboflavin 	","	Riboflavine 	"},
		{"	Rifampicina	","	Rifampicin 	","	Rifampicine 	"},
		{"	Rifaximina	","	Rifaximin 	","	Rifaximin 	"},
		{"	Riluzol	","	Riluzole 	","	Riluzole 	"},
		{"	Rimexolona	","	Rimexolone 	","	Rimexolone 	"},
		{"	Risperidona	","	Risperidone 	","	La rispéridone 	"},
		{"	Ritonavir	","	Ritonavir 	","	Ritonavir 	"},
		{"	Rivastigmina	","	Rivastigmine 	","	Rivastigmine 	"},
		{"	Rizatriptán	","	Rizatriptan 	","	Rizatriptan 	"},
		{"	Ropinirol	","	Ropinirole 	","	Le ropinirole 	"},
		{"	Ropivacaína	","	Ropivacaine 	","	La ropivacaïne 	"},
		{"	Rosiglitazona	","	Rosiglitazone 	","	Rosiglitazone 	"},
		{"	Rosuvastatina	","	Rosuvastatin 	","	Rosuvastatine 	"},
		{"	Roxatidina	","	Roxatidine 	","	Roxatidine 	"},
		{"	Roxitromicina	","	Roxithromycin 	","	Roxithromycine 	"},
		{"	Rupatadina	","	Rupatadine 	","	Rupatadine 	"},
		{"	Ruscus aculeatus	","	Ruscus aculeatus 	","	Ruscus aculeatus 	"},
		{"	Saccharomyces boulardii	","	Saccharomyces boulardii 	","	Saccharomyces boulardii 	"},
		{"	Salbutamol	","	Salbutamol 	","	Salbutamol 	"},
		{"	Salicilamida	","	Salicylamide 	","	Salicylamide 	"},
		{"	Salmeterol	","	Salmeterol 	","	Salmétérol 	"},
		{"	Saquinavir	","	Saquinavir 	","	Saquinavir 	"},
		{"	Senósidos A + B	","	Sennosides A + B 	","	Sennosides A + B 	"},
		{"	Serenoa repens	","	Serenoa repens 	","	Repens de Serenoa 	"},
		{"	Sertindol	","	Sertindole 	","	Sertindole 	"},
		{"	Sertralina	","	Sertraline 	","	Sertraline 	"},
		{"	Sevelamer	","	Sevelamer 	","	Sevelamer 	"},
		{"	Sibutramina	","	Sibutramine 	","	Sibutramine 	"},
		{"	Sildenafilo	","	Sildenafil 	","	Sildenafil 	"},
		{"	Silodosina	","	Silodosin 	","	Silodosin 	"},
		{"	Simeticona	","	Simethicone 	","	Simethicone 	"},
		{"	Simvastatina	","	Simvastatin 	","	Simvastatine 	"},
		{"	Sirolimus	","	Sirolimus 	","	Sirolimus 	"},
		{"	Sitagliptina	","	Sitagliptin 	","	La sitagliptine 	"},
		{"	Sobrerol	","	Sobrerol 	","	Sobrerol 	"},
		{"	Sodio	","	Sodium 	","	Sodium 	"},
		{"	Soja	","	Soy 	","	Soja 	"},
		{"	Solifenacina	","	Solifenacin 	","	La solifénacine 	"},
		{"	Somatostatina	","	Somatostatin 	","	Somatostatine 	"},
		{"	Sotalol	","	Sotalol 	","	Sotalol 	"},
		{"	Sucralfato	","	Sucralfate 	","	Sucralfate 	"},
		{"	Sulfadiazina	","	Sulfadiazine 	","	Sulfadiazine 	"},
		{"	Sulfametoxazol	","	Sulfamethoxazole 	","	Sulfaméthoxazole 	"},
		{"	Sulpirida	","	Sulpiride 	","	Sulpiride 	"},
		{"	Sultamicilina	","	Sultamicillin 	","	Sultamicilline 	"},
		{"	Sumatriptán	","	Sumatriptan 	","	Sumatriptan 	"},
		{"	Suxametonio	","	Suxamethonium 	","	Suxaméthonium 	"},
		{"	Tacrolimus	","	Tacrolimus 	","	Tacrolimus 	"},
		{"	Tadalafilo	","	Tadalafil 	","	Tadalafil 	"},
		{"	Tamoxifeno	","	Tamoxifen 	","	Le tamoxifène 	"},
		{"	Tamsulosina	","	Tamsulosin 	","	Tamsulosine 	"},
		{"	Tazaroteno	","	Tazarotene 	","	Tazarotène 	"},
		{"	Tazobactam	","	Tazobactam 	","	Tazobactam 	"},
		{"	Tegafur	","	Tegafur 	","	Tégafur 	"},
		{"	Teicoplanina	","	Teicoplanin 	","	Teicoplanin 	"},
		{"	Telbivudina	","	Telbivudine 	","	La telbivudine 	"},
		{"	Telitromicina	","	Telithromycin 	","	Télithromycine 	"},
		{"	Telmisartán	","	Telmisartan 	","	Le telmisartan 	"},
		{"	Temozolomida	","	Temozolomide 	","	Témozolomide 	"},
		{"	Tenofovir	","	Tenofovir 	","	Le ténofovir 	"},
		{"	Tenoxicam	","	Tenoxicam 	","	Tenoxicam 	"},
		{"	Terazosina	","	Terazosin 	","	Térazosine 	"},
		{"	Terbinafina	","	Terbinafine 	","	La terbinafine 	"},
		{"	Terbutalina	","	Terbutaline 	","	Terbutaline 	"},
		{"	Testosterona	","	Testosterone 	","	La testostérone 	"},
		{"	Tetracaína	","	Tetracaine 	","	Tétracaïne 	"},
		{"	Tetrazepam	","	Tetrazepam 	","	Tetrazepam 	"},
		{"	Tetrizolina	","	Tetryzoline 	","	Tétryzoline 	"},
		{"	Tiagabina	","	Tiagabine 	","	Tiagabine 	"},
		{"	Tiamina	","	Thiamine 	","	Thiamine 	"},
		{"	Tiaprida	","	Thiapride 	","	Thiapride 	"},
		{"	Tibolona	","	Tibolone 	","	Tibolone 	"},
		{"	Ticlopidina	","	Ticlopidine 	","	Ticlopidine 	"},
		{"	Timol	","	Thymol 	","	Thymol 	"},
		{"	Timolol	","	Timolol 	","	Timolol 	"},
		{"	Tinidazol	","	Tinidazole 	","	Tinidazole 	"},
		{"	Tioconazol	","	Tioconazole 	","	Tioconazole 	"},
		{"	Tioguanina	","	Thioguanine 	","	Thioguanine 	"},
		{"	Tiomersal	","	Thimerosal 	","	Le thimérosal 	"},
		{"	Tiotropio	","	Tiotropium 	","	Tiotropium 	"},
		{"	Tirotricina	","	Tyrothricin 	","	Tyrothricin 	"},
		{"	Tizanidina	","	Tizanidine 	","	Tizanidine 	"},
		{"	Tobramicina	","	Tobramycin 	","	Tobramycine 	"},
		{"	Tolcapone	","	Tolcapone 	","	Tolcapone 	"},
		{"	Tolnaftato	","	Tolnaftate 	","	Tolnaftate 	"},
		{"	Tolterodina	","	Tolterodine 	","	Toltérodine 	"},
		{"	Tomillo	","	Thyme 	","	Thym 	"},
		{"	Topiramato	","	Topiramate 	","	Topiramate 	"},
		{"	Torasemida	","	Torasemide 	","	Torasemide 	"},
		{"	Toremifeno	","	Toremifene 	","	Torémifène 	"},
		{"	Tramadol	","	Tramadol 	","	Tramadol 	"},
		{"	Trandolapril	","	Trandolapril 	","	Trandolapril 	"},
		{"	Trazodona	","	Trazodone 	","	Trazodone 	"},
		{"	Trementina	","	Turpentine 	","	Essence de térébenthine 	"},
		{"	Tretinoína	","	Tretinoin 	","	La trétinoïne 	"},
		{"	Triamcinolona	","	Triamcinolone 	","	Triamcinolone 	"},
		{"	Triamtereno	","	Triamterene 	","	Triamterene 	"},
		{"	Triflusal	","	Triflusal 	","	Triflusal 	"},
		{"	Trifolium pratense	","	Trifolium pratense 	","	Trifolium pratense 	"},
		{"	Trimetazidina	","	Trimetazidine 	","	Trimétazidine 	"},
		{"	Trimetoprima	","	Trimethoprim 	","	Triméthoprime 	"},
		{"	Trimipramina	","	Trimipramine 	","	Trimipramine 	"},
		{"	Triprolidina	","	Triprolidine 	","	Triprolidine 	"},
		{"	Tropisetron	","	Tropisetron 	","	Tropisetron 	"},
		{"	Troxerutina	","	Troxerutine 	","	Troxérutine 	"},
		{"	Tuaminoheptano	","	Tuaminoheptane 	","	Tuaminoheptane 	"},
		{"	Ulipristal	","	Ulipristal 	","	Ulipristal 	"},
		{"	Uracilo	","	Uracil 	","	Uracile 	"},
		{"	Urea	","	Urea 	","	Urée 	"},
		{"	Valaciclovir	","	Valaciclovir 	","	Le valaciclovir 	"},
		{"	Valeriana officinalis	","	Valeriana officinalis 	","	Valeriana officinalis 	"},
		{"	Valganciclovir	","	Valganciclovir 	","	Valganciclovir 	"},
		{"	Valpromida	","	Valpromide 	","	Valpromide 	"},
		{"	Valsartán	","	Valsartan 	","	Valsartan 	"},
		{"	Vancomicina	","	Vancomycin 	","	Vancomycine 	"},
		{"	Vardenafilo	","	Vardenafil 	","	Vardenafil 	"},
		{"	Vareniclina	","	Varenicline 	","	La varénicline 	"},
		{"	Vecuronio	","	Vecuronium 	","	Vecuronium 	"},
		{"	Venlafaxina	","	Venlafaxine 	","	Venlafaxine 	"},
		{"	Verapamilo	","	Verapamil 	","	Vérapamil 	"},
		{"	Vid roja	","	Red vine 	","	La vigne rouge 	"},
		{"	Vildagliptina	","	Vildagliptin 	","	Vildagliptine 	"},
		{"	Vinorelbina	","	Vinorelbine 	","	Vinorelbine 	"},
		{"	Vinpocetina	","	Vinpocetine 	","	Vinpocetine 	"},
		{"	Violeta genciana	","	Gentian violet 	","	Violet de gentiane 	"},
		{"	Virus rabia	","	Rabies virus 	","	Virus de la rage 	"},
		{"	Virus rubéola	","	Rubella virus 	","	Virus de la rubéole 	"},
		{"	Vitamina A	","	Vitamin A 	","	La vitamine A 	"},
		{"	Vitamina B12	","	Vitamin B12 	","	La vitamine B12 	"},
		{"	Vitamina E	","	Vitamin E 	","	La vitamine E 	"},
		{"	Vitex agnus castus	","	Vitex agnus castus 	","	Vitex agnus castus 	"},
		{"	Warfarina	","	Warfarin 	","	Warfarine 	"},
		{"	Xilometazolina	","	Xylometazoline 	","	xylométazoline 	"},
		{"	Yodo	","	Iodine 	","	Iode 	"},
		{"	Yoduro de potasio	","	Potassium iodide 	","	L´iodure de potassium 	"},
		{"	Zafirlukast	","	Zafirlukast 	","	Zafirlukast 	"},
		{"	Zidovudina	","	Zidovudine 	","	Zidovudine 	"},
		{"	Zinc	","	Zinc 	","	Zinc 	"},
		{"	Ziprasidona	","	Ziprasidone 	","	Ziprasidone 	"},
		{"	Zofenopril	","	Zofenopril 	","	Zofenopril 	"},
		{"	Zolmitriptán	","	Zolmitriptan 	","	Zolmitriptan 	"},
		{"	Zolpidem	","	Zolpidem 	","	Zolpidem 	"},
		{"	Zonisamida	","	Zonisamide 	","	Le zonisamide 	"},
		{"	Zopiclona	","	Zopiclone 	","	Zopiclone 	"},
		{"	Zuclopentixol	","	Zuclopenthixol	","	Zuclopenthixol	"}		
		};
}
